# Generated by Django 4.2.5 on 2023-10-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
